In [1]:
!pip install numpy

In [2]:
import numpy as np

## 1. Create

In [ ]:
[[1,2,3,4], [1,2,2,2]]

In [9]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))


In [10]:
data

array([[[0.06167603, 0.54381187, 0.80698401, 0.73279922],
        [0.52200979, 0.76367442, 0.52378554, 0.65596538],
        [0.24863424, 0.78640785, 0.11004319, 0.36176569]],

       [[0.77794021, 0.90003727, 0.31470254, 0.79972662],
        [0.83841376, 0.21753593, 0.44292149, 0.38373475],
        [0.32514136, 0.26111019, 0.36785891, 0.50813218]]])

In [11]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [12]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [13]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [15]:
arr = np.array([[1,2,3,4], [1,2,3,4]])

In [16]:
type(arr)

numpy.ndarray

## 2. Read

In [20]:
shape = data.shape
size = data.size
types = data.dtype

In [21]:
shape

(2, 3, 4)

In [22]:
size

24

In [23]:
types

dtype('float64')

In [26]:
#slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singlevel = data[0][0][0]

In [28]:
slicer

array([[0.06167603, 0.54381187, 0.80698401, 0.73279922],
       [0.52200979, 0.76367442, 0.52378554, 0.65596538]])

In [29]:
reverse

array([[0.77794021, 0.90003727, 0.31470254, 0.79972662],
       [0.83841376, 0.21753593, 0.44292149, 0.38373475],
       [0.32514136, 0.26111019, 0.36785891, 0.50813218]])

In [30]:
singlevel

np.float64(0.061676026073710366)

## 3. Update

In [31]:
data

array([[[0.06167603, 0.54381187, 0.80698401, 0.73279922],
        [0.52200979, 0.76367442, 0.52378554, 0.65596538],
        [0.24863424, 0.78640785, 0.11004319, 0.36176569]],

       [[0.77794021, 0.90003727, 0.31470254, 0.79972662],
        [0.83841376, 0.21753593, 0.44292149, 0.38373475],
        [0.32514136, 0.26111019, 0.36785891, 0.50813218]]])

In [32]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [33]:
list1

array([0.7216602 , 0.04886639, 0.59067592, 0.30411065, 0.62978642,
       0.48516572, 0.78724087, 0.5264932 , 0.39067921, 0.89878301])

In [34]:
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)


In [37]:
mult

array([0.0789801 , 0.03076858, 0.16552666, 0.08457479, 0.52252336,
       0.39659654, 0.2367443 , 0.27569535, 0.24758661, 0.42914452])

In [41]:
# statistical functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2, 3)
log = np.log(25)
exp = np.exp([2, 3])
mins = np.min(list1)
maxs = np.max(list2)

In [42]:
maxs

np.float64(0.8296834390728964)

In [43]:
data

array([[[0.06167603, 0.54381187, 0.80698401, 0.73279922],
        [0.52200979, 0.76367442, 0.52378554, 0.65596538],
        [0.24863424, 0.78640785, 0.11004319, 0.36176569]],

       [[0.77794021, 0.90003727, 0.31470254, 0.79972662],
        [0.83841376, 0.21753593, 0.44292149, 0.38373475],
        [0.32514136, 0.26111019, 0.36785891, 0.50813218]]])

In [44]:
data[0][0][0] = 700

In [45]:
data

array([[[7.00000000e+02, 5.43811872e-01, 8.06984010e-01, 7.32799222e-01],
        [5.22009789e-01, 7.63674421e-01, 5.23785539e-01, 6.55965377e-01],
        [2.48634241e-01, 7.86407850e-01, 1.10043189e-01, 3.61765686e-01]],

       [[7.77940207e-01, 9.00037273e-01, 3.14702541e-01, 7.99726625e-01],
        [8.38413762e-01, 2.17535926e-01, 4.42921494e-01, 3.83734749e-01],
        [3.25141362e-01, 2.61110192e-01, 3.67858914e-01, 5.08132182e-01]]])

In [46]:
data.sort()

In [47]:
data

array([[[5.43811872e-01, 7.32799222e-01, 8.06984010e-01, 7.00000000e+02],
        [5.22009789e-01, 5.23785539e-01, 6.55965377e-01, 7.63674421e-01],
        [1.10043189e-01, 2.48634241e-01, 3.61765686e-01, 7.86407850e-01]],

       [[3.14702541e-01, 7.77940207e-01, 7.99726625e-01, 9.00037273e-01],
        [2.17535926e-01, 3.83734749e-01, 4.42921494e-01, 8.38413762e-01],
        [2.61110192e-01, 3.25141362e-01, 3.67858914e-01, 5.08132182e-01]]])

In [48]:
print(data.shape)

(2, 3, 4)


In [51]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [54]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [55]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


## 4. Delete

In [61]:
data

array([[[5.43811872e-01, 7.32799222e-01, 8.06984010e-01, 7.00000000e+02,
         5.22009789e-01, 5.23785539e-01],
        [6.55965377e-01, 7.63674421e-01, 1.10043189e-01, 2.48634241e-01,
         3.61765686e-01, 7.86407850e-01]],

       [[3.14702541e-01, 7.77940207e-01, 7.99726625e-01, 9.00037273e-01,
         2.17535926e-01, 3.83734749e-01],
        [4.42921494e-01, 8.38413762e-01, 2.61110192e-01, 3.25141362e-01,
         3.67858914e-01, 5.08132182e-01]]])

In [62]:
np.delete(data, 0, axis=1)

array([[[0.65596538, 0.76367442, 0.11004319, 0.24863424, 0.36176569,
         0.78640785]],

       [[0.44292149, 0.83841376, 0.26111019, 0.32514136, 0.36785891,
         0.50813218]]])

In [65]:
np.save("new array", data)

In [66]:
# to reload the array
test = np.load("new array.npy")
test

array([[[5.43811872e-01, 7.32799222e-01, 8.06984010e-01, 7.00000000e+02,
         5.22009789e-01, 5.23785539e-01],
        [6.55965377e-01, 7.63674421e-01, 1.10043189e-01, 2.48634241e-01,
         3.61765686e-01, 7.86407850e-01]],

       [[3.14702541e-01, 7.77940207e-01, 7.99726625e-01, 9.00037273e-01,
         2.17535926e-01, 3.83734749e-01],
        [4.42921494e-01, 8.38413762e-01, 2.61110192e-01, 3.25141362e-01,
         3.67858914e-01, 5.08132182e-01]]])