In [1]:
import numpy as np

In [2]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [4]:
z = x[1:4, 2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [5]:
z = x[:3, 2:]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [6]:
z = x[:3, 2:]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [7]:
z = x[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [9]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [10]:
z[2, 2] = 555
print(z)

IndexError: index 2 is out of bounds for axis 1 with size 1

In [16]:
b = np.arange(1, 21).reshape(4, 5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
indices = np.array([1, 3])
print(indices)

[1 3]


In [18]:
y = x[indices, :]

In [20]:
print(y)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [21]:
z = np.diag(x, k=1)
print(z)

[ 2  8 14 20]


In [22]:
z = np.diag(x, k=-1)
print(z)

[ 6 12 18]


In [23]:
x = np.array([[1, 2, 3], [5, 2, 8], [1, 2, 3]])
print(x)

[[1 2 3]
 [5 2 8]
 [1 2 3]]


In [24]:
print(np.unique(x))

[1 2 3 5 8]


### Boolean Indexing, Set Operations, and Sorting

In [25]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [26]:
print(x[x > 10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [27]:
print(x[x <= 7])
print(x)

[0 1 2 3 4 5 6 7]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [40]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

In [41]:
print(np.intersect1d(x,y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))


[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [42]:
x = np.random.randint(1, 11, size=(10,))
print(x)

[ 6  6  8  7  6  4  7  5 10  4]


In [43]:
x.sort()
print(x)

[ 4  4  5  6  6  6  7  7  8 10]


In [44]:
print(np.sort(x))
print(x)

[ 4  4  5  6  6  6  7  7  8 10]
[ 4  4  5  6  6  6  7  7  8 10]


In [45]:
print(np.sort(np.unique(x)))
print(x)

[ 4  5  6  7  8 10]
[ 4  4  5  6  6  6  7  7  8 10]


In [49]:
x = np.random.randint(1, 11, size=(5,5))
print()
print('Original X = \n', x)
print()

print()
print('X with sorted columns :\n', np.sort(x, axis = 0))

print()
print('X with sorted rows :\n', np.sort(x, axis = 1))


Original X = 
 [[8 5 6 6 4]
 [1 7 5 4 1]
 [2 9 2 5 3]
 [8 1 7 6 4]
 [6 5 1 6 7]]


X with sorted columns :
 [[1 1 1 4 1]
 [2 5 2 5 3]
 [6 5 5 6 4]
 [8 7 6 6 4]
 [8 9 7 6 7]]

X with sorted rows :
 [[4 5 6 6 8]
 [1 1 4 5 7]
 [2 2 3 5 9]
 [1 4 6 7 8]
 [1 5 6 6 7]]


### Create a 5 x 5 ndarray X with consecutive integers from 1 to 25 (inclusive). Afterwards use Boolean indexing to pick out only the odd numbers in the array and assign the result to Y.

In [52]:
import numpy as np

# TODO: replace None with appropriate code
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1, 26).reshape(5, 5)

# TODO: replace None with appropriate code
# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 != 0]

### Notebook grading
X_solution = np.arange(1,26).reshape(5,5)
Y_solution= X_solution[X_solution % 2 != 0]

if type(X) != np.ndarray or type(Y) != np.ndarray:
    print("`X` and `Y` should both be ndarrays")
elif np.array_equal(X, X_solution) and np.array_equal(Y, Y_solution):
    print("Nice work! You can view my solution below")
elif X.shape != X_solution.shape:
    print("Your answer for `X` has a shape of {} but it should be 5 x 5".format(X.shape))
elif len(Y) != len(Y_solution):
    print("Your answer for `Y` has a length of {} but it should have a length of 13".format(len(Y)))
else:
    print("Your answers have the right shape but incorrect values")

Nice work! You can view my solution below


## Arithmetic operations and Broadcasting

In [53]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [54]:
print(x + y)
print(np.add(x, y))

[ 6  8 10 12]
[ 6  8 10 12]


In [57]:
print(x - y)
print(x * y)
print(x / y)

[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [58]:
print(x)

[1 2 3 4]


In [60]:
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [61]:
# you can calculate for mean, median,std dev, minimum, maximum, etc.

In [62]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


## nd-arrays broadcasting

In [66]:
import numpy as np

# Replace None with appropriate code
X = np.ones((4,4)) * np.arange(1,5)
print(X)
### Notebook grading
solution = np.ones((4,4)) * np.arange(1,5)
if type(X) != np.ndarray:
    print("`X` should be an ndarray")
elif np.array_equal(X, solution):
    print("Nice work! You can view my solution below")
elif X.shape != solution.shape:
    print("Your answer for `X` has a shape of {} but it should be 4 x 4".format(X.shape))
else:
    print("Your answer for `X` has the right shape but incorrect values")

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
Nice work! You can view my solution below
