In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [4]:
print('1st element:', x[0])
print('1st element:', x[-1])
print('1st element:', x[-4])

1st element: 1
1st element: 5
1st element: 2


In [5]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [7]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
x[0,0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [10]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.delete(x, [0, 4])
print(x)

[1 2 3 4 5]
[2 3 4]


In [12]:
y = np.arange(1, 10).reshape(3, 3)
print(y)

w = np.delete(y, 0, axis=0)
print(w)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]


In [13]:

x = np.append(x, 6)
print(x)

[2 3 4 6]


In [14]:
x = np.append(x, 6)
print(x)

[2 3 4 6 6]


In [15]:
x = np.append(x, [7, 8])
print(x)

In [18]:
# appending rows
w = np.append(y, [[10, 11, 12]], axis=0)
print(w)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
v = np.append(y, [[10], [11], [12]], axis=1)
print(v)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
